server:
  port: 8080
  servlet:
    context-path: /api
spring:
  session:
    storage-type: redis  # 使用 Redis 存储会话
    timeout: 2592000  # 会话超时时间，单位为秒
  data:
    redis:
      host: localhost   # Redis 地址
      port: 6379        # Redis 端口
      database: 0      # Redis 数据库索引
      timeout: 5000ms   # 连接超时时间，可根据需求调整
  application:
    name: picture-backend
  datasource:
    url: jdbc:mysql://localhost:3306/picture_backend
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  profiles:
    active: local  # 设置当前激活的配置文件为 local
  servlet:
    multipart:
      max-file-size: 10MB  # 设置上传文件的最大大小
  main:
    allow-circular-references: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic_delete-field: isDeleted
        logic_delete-value: 1
        logic_not_delete-value: 0
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.bxt.picture.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

